Repository apu52/METAVERSE, pull requests merged in 2023-11, with the labels that each got.

#126 added a reset button to reset the date
  Projects/Age Calculator/index.html
  Projects/Age Calculator/script.js
  Projects/Age Calculator/style.css
Labels: enhancement, OSEN, SIMPLE

#130 Music player clone
  Index.html.md
  Projects/Music Player/Images/Screenshot 2023-11-10 055228.png
  Projects/Music Player/Readme.md
  Projects/Music Player/Single_Playlist_Screen.html
  Projects/Music Player/Single_Playlist_Screen_Styles.css
  Projects/Music Player/index.html
Labels: New project, OSEN, MEDIUM

#135 Meme generator
  Index.html.md
  Projects/Meme Generator/Readme.md
  Projects/Meme Generator/index.html
  Projects/Meme Generator/script.js
  Projects/Meme Generator/style.css
Labels: enhancement, OSEN, SIMPLE

#144 Quote generator
  Index.html.md
  Projects/Quote Generator/Readme.md
  Projects/Quote Generator/index.html
  Projects/Quote Generator/script.js
  Projects/Quote Generator/style.css
Labels: enhancement, OSEN, SIMPLE

#153 Spotify-CLone
  Projects/Spotify_Clone/README.md
  Projects/Spotify_Clone/assets/backward_icon.png
  Projects/Spotify_Clone/assets/card1img.jpeg
  Projects/Spotify_Clone/assets/card2img.jpeg
  Projects/Spotify_Clone/assets/card3img.jpeg
  Projects/Spotify_Clone/assets/card4img.jpeg
  Projects/Spotify_Clone/assets/card5img.jpeg
  Projects/Spotify_Clone/assets/card6img.jpeg
  Projects/Spotify_Clone/assets/forward_icon.png
  Projects/Spotify_Clone/assets/library_icon.png
  Projects/Spotify_Clone/assets/logo.png
  Projects/Spotify_Clone/assets/play_musicbar.png
  Projects/Spotify_Clone/assets/player_icon1.png
  Projects/Spotify_Clone/assets/player_icon2.png
  Projects/Spotify_Clone/assets/player_icon3.png
  Projects/Spotify_Clone/assets/player_icon4.png
  Projects/Spotify_Clone/assets/player_icon5.png
  Projects/Spotify_Clone/index.html
  Projects/Spotify_Clone/style.css
  assets/img/Spotify_Clone.png
  projectData.json
Labels: New project, OSEN, SIMPLE
