Repository apu52/METAVERSE, pull requests merged in 2023-10, with the labels that each got.

#19 Stopwatch
  Index.html.md
  Projects/Stopwatch/README.md
  Projects/Stopwatch/index.html
  Projects/Stopwatch/script.js
  Projects/Stopwatch/style.css
Labels: New project, hacktoberfest-accepted

#21 Branch 2(Weather application)
  .vscode/settings.json
  Index.html.md
  Projects/Weather_application/README.md
  Projects/Weather_application/background.jpg
  Projects/Weather_application/index.html
  Projects/Weather_application/script.js
  Projects/Weather_application/style.css
  Projects/Weather_application/unknown.pct
Labels: review requested

#32 Book review website
  Index.html.md
  Projects/Book_review_website/README.md
  Projects/Book_review_website/Screenshot 2023-10-15 111827.png
  Projects/Book_review_website/Screenshot 2023-10-15 111845.png
  Projects/Book_review_website/Screenshot 2023-10-15 111912.png
  Projects/Book_review_website/book1.jpeg
  Projects/Book_review_website/index.html
  Projects/Book_review_website/libimg2.jpg
  Projects/Book_review_website/set1.jpg
  Projects/Book_review_website/set2.jpeg
  Projects/Book_review_website/set3.jpeg
  Projects/Book_review_website/set4.jpeg
  Projects/Book_review_website/style.css
Labels: good first issue, New project

#34 Created QR ID CARD GENERATOR
  Index.html.md
  Projects/QR_ID_Card_Generator/.DS_Store
  Projects/QR_ID_Card_Generator/README.md
  Projects/QR_ID_Card_Generator/background.jpg
  Projects/QR_ID_Card_Generator/demo.png
  Projects/QR_ID_Card_Generator/index.html
  Projects/QR_ID_Card_Generator/script.js
  Projects/QR_ID_Card_Generator/style.css
Labels: good first issue, New project

#58 A-Netflix-Clone
  Projects/Netflix_clone_Project/README.md
  Projects/Netflix_clone_Project/image-1.png
  Projects/Netflix_clone_Project/image.png
  Projects/Netflix_clone_Project/index.css
  Projects/Netflix_clone_Project/index.html
  Projects/Netflix_clone_Project/index.js
Labels: New project, OSEN, MEDIUM

#66 Update Index.html.md
  Index.html.md
Labels: enhancement

#80 Survey form
  Index.html.md
  Survey Form/README.md
  Survey Form/index.html
  Survey Form/style.css
Labels: review requested

#78 Log in page
  Index.html.md
  LogIn Page/README.md
  LogIn Page/index.html
  LogIn Page/style.css
Labels: review requested

#92 Improve metaverse poster
  README.md
  images/Metaverse poster.gif
Labels: enhancement, good first issue, OSEN, SIMPLE
