Repository apu52/METAVERSE, pull requests merged in 2024-06, with the labels that each got.

#704 fixed the animated text on contact page for mobile
  assets/css/style.css
  contact.html
Labels: help wanted, review requested

#713 changed the layout for owner info on mobile to fix the overlap
  assets/css/style.css
  contact.html
Labels: review requested, changesrequested, PENDING

#715 Fixed Social Media links in the About Page!
  about.html
  contact.html
Labels: review requested

#720 Added dark theme to contact page
  assets/css/about.css
  assets/css/style.css
  contact.html
Labels: help wanted, changesrequested

#753 Added Styles and hovering effect and animations to the organica website
  Projects/organica/assets/css/home.css
Labels: bug, gssoc, level3

#748 Adding a back button for the sidebar and more
  Projects/Career-Crafters/app.js
  Projects/Career-Crafters/index.html
  Projects/Chat_App/src/styles/style.css
Labels: help wanted, changesrequested, PENDING

#788 Added styles hovering effect and transitions to blog website
  Projects/Blog_Website/index.html
  Projects/Blog_Website/post.html
  Projects/Blog_Website/style.css
Labels: bug, changesrequested

#800 Enchanced the UI for footer and about us section in Food Order Website.
  Projects/Food_Ordering_Website/index.html
  Projects/Food_Ordering_Website/style.css
  Projects/Hotsar_Clone/Contributing.md
  Projects/Hotsar_Clone/Contributors.md
Labels: changesrequested

#798 Fixed the broken link for Hotstar clone website
  Projects/Hotsar_Clone/Contributing.md
  Projects/Hotsar_Clone/Contributors.md
Labels: changesrequested
