Repository apu52/METAVERSE, pull requests merged in 2024-07, with the labels that each got.

#869 Add Sign-In/Sign-Up Functionality with Menu and Database Integration
  Projects/Book_review_website/README.md
  Projects/Book_review_website/ScreenShots/Screenshot 2023-10-15 111827.png
  Projects/Book_review_website/ScreenShots/Screenshot 2023-10-15 111845.png
  Projects/Book_review_website/ScreenShots/Screenshot 2023-10-15 111912.png
  Projects/Book_review_website/index.html
  Projects/Book_review_website/main.js
  Projects/Book_review_website/package-lock.json
  Projects/Book_review_website/package.json
  Projects/Book_review_website/public/config/firebaseConfig.js
  Projects/Book_review_website/public/css/header.css
  Projects/Book_review_website/public/css/signin.css
  Projects/Book_review_website/public/css/style.css
  Projects/Book_review_website/public/images/book1.jpeg
  Projects/Book_review_website/public/images/libimg2.jpg
  Projects/Book_review_website/public/images/openbook1.webp
  Projects/Book_review_website/public/images/rev1.jpg
  Projects/Book_review_website/public/images/rev2.jpg
  Projects/Book_review_website/public/images/rev3.jpg
  Projects/Book_review_website/public/images/set1.jpg
  Projects/Book_review_website/public/images/set2.jpeg
  Projects/Book_review_website/public/images/set3.jpeg
  Projects/Book_review_website/public/images/set4.jpeg
  Projects/Book_review_website/public/package-lock.json
  Projects/Book_review_website/public/package.json
  Projects/Book_review_website/public/scripts/main.js
  Projects/Book_review_website/public/scripts/signin.js
  Projects/Book_review_website/public/scripts/signup.js
  Projects/Book_review_website/public/signin.html
  Projects/Book_review_website/public/signup.html
  Projects/Book_review_website/server.js
  Projects/Book_review_website/signin.html
  Projects/Book_review_website/signup.html
  package-lock.json
  package.json
Labels: help wanted, changesrequested

#875 Blog Website - GreatZone UI Improved
  Projects/Blog_Website/index.html
  Projects/Blog_Website/style.css
  assets/img/Blog_Website.png
Labels: help wanted, PENDING

#801 Complete and Enhance the Home Page for Netflix Clone( DONE)
  Projects/Netflix_clone_Project/index.css
  Projects/Netflix_clone_Project/index.html
  Projects/Netflix_clone_Project/index.js
Labels: changesrequested

#924 added check for empty tasks
  Projects/To-Do_List_Project/index.html
Labels: help wanted, changesrequested

#870 logo is added in career crafters
  Projects/Career-Crafters/index.html
Labels: help wanted, changesrequested

#963 [BUG FIX] Renamed the Codeforces API Project to its actual name- Rock Paper Scissors game
  Projects/Rock-Paper-Scissors-2/index.html
  Projects/Rock-Paper-Scissors-2/index.js
  Projects/Rock-Paper-Scissors-2/package-lock.json
  Projects/Rock-Paper-Scissors-2/package.json
  Projects/Rock-Paper-Scissors-2/public/Styles/index.css
  Projects/Rock-Paper-Scissors-2/public/Styles/nav.css
  Projects/Rock-Paper-Scissors-2/public/Styles/problems.css
  Projects/Rock-Paper-Scissors-2/public/Styles/user_info.css
  Projects/Rock-Paper-Scissors-2/public/images/codeforces.png
  Projects/Rock-Paper-Scissors-2/public/images/icon.png
  Projects/Rock-Paper-Scissors-2/rock-paper-scissor-photos/paper-emoji.png
  Projects/Rock-Paper-Scissors-2/rock-paper-scissor-photos/rock-emoji.png
  Projects/Rock-Paper-Scissors-2/rock-paper-scissor-photos/scissor-emoji.png
  Projects/Rock-Paper-Scissors-2/rps-script.js
  Projects/Rock-Paper-Scissors-2/rps.css
  Projects/Rock-Paper-Scissors-2/views/index.ejs
  Projects/Rock-Paper-Scissors-2/views/partials/footer.ejs
  Projects/Rock-Paper-Scissors-2/views/partials/navbar.ejs
  Projects/Rock-Paper-Scissors-2/views/problem_result.ejs
  Projects/Rock-Paper-Scissors-2/views/problems.ejs
  Projects/Rock-Paper-Scissors-2/views/user_info.ejs
  assets/img/Rock-Paper-Scissors-2.png
  projectData.json
Labels: changesrequested

#973 Created a New Cursor Trail effect to Improve UI/UX
  about.html
  assets/css/cursor_transition.css
  assets/js/mouse_transition.js
  contact.html
  copyright.html
  index.html
  privacynotice.html
Labels: changesrequested

#998 Feat: Sending mail on netflix membership
  Projects/Netflix_clone_Project/index.html
  Projects/Netflix_clone_Project/index.js
Labels: changesrequested

#979 Corrected Temperature converter logic and Added Background image.
  Projects/Temperature_Converter/index.html
  Projects/Temperature_Converter/main.js
  Projects/Temperature_Converter/style.css
Labels: changesrequested

#1043 add faq in tindog website
  Projects/Tindog_website/index.html
  Projects/Tindog_website/style.css
Labels: changesrequested

#1057 Navbar in Restaurant Website is added
  Projects/Restaurant_Website/index.html
  Projects/Restaurant_Website/style.css
Labels: review requested

#940 [Feature Request]: want to improve country guide app i wll almost renew the Ui #852
  Projects/Country_Guide/Main/.gitignore
  Projects/Country_Guide/Main/README.md
  Projects/Country_Guide/Main/components/card.js
  Projects/Country_Guide/Main/components/cardDetails.js
  Projects/Country_Guide/Main/components/loader.js
  Projects/Country_Guide/Main/components/navigation.js
  Projects/Country_Guide/Main/country-guide.svg
  Projects/Country_Guide/Main/css/style.css
  Projects/Country_Guide/Main/css/style.css.map
  Projects/Country_Guide/Main/index.html
  Projects/Country_Guide/Main/main.js
  Projects/Country_Guide/Main/modules/api.js
  Projects/Country_Guide/Main/modules/functions.js
  Projects/Country_Guide/Main/modules/switchMode.js
  Projects/Country_Guide/Main/package-lock.json
  Projects/Country_Guide/Main/package.json
  Projects/Country_Guide/Main/public/country-guide.svg
  Projects/Country_Guide/Main/sass/_custom.scss
  Projects/Country_Guide/Main/sass/design/_cardDisplay.scss
  Projects/Country_Guide/Main/sass/design/_cards.scss
  Projects/Country_Guide/Main/sass/design/_functions.scss
  Projects/Country_Guide/Main/sass/design/_loader.scss
  Projects/Country_Guide/Main/sass/design/_mixin.scss
  Projects/Country_Guide/Main/sass/design/_navigation.scss
  Projects/Country_Guide/Main/sass/design/_variables.scss
  Projects/Country_Guide/Main/sass/style.scss
  Projects/Country_Guide/Main/style-guide.md
  Projects/Country_Guide/country.jpg
  Projects/Country_Guide/country.png
  Projects/Country_Guide/index.html
  Projects/Country_Guide/script.js
  Projects/Country_Guide/style.css
  assets/img/Country_Guide.png
Labels: help wanted, changesrequested

#1095 Added Sign-In page to netflix clone.
  Projects/Netflix_clone_Project/Netflix-logo.png
  Projects/Netflix_clone_Project/image-bg.png
  Projects/Netflix_clone_Project/index.html
  Projects/Netflix_clone_Project/sigin.html
  Projects/Netflix_clone_Project/signin.css
Labels: enhancement, gssoc, level2

#1096 Added sign up and login page in food website clone
  Projects/Food_Website/Images/signin3.jpg
  Projects/Food_Website/index.html
  Projects/Food_Website/profile.css
  Projects/Food_Website/profile.html
Labels: enhancement, gssoc, level2

#1028 Temperature Converter UI Improved
  Projects/Temperature_Converter/Temperature Converter.png
  Projects/Temperature_Converter/bgimg.jpg
  Projects/Temperature_Converter/style.css
  assets/img/Temperature_Converter.png
Labels: help wanted
