Repository apu52/METAVERSE, pull requests merged in 2024-01, with the labels that each got.

#595 Added new project : Astronomy picture of the day
  Projects/Astronomy/README.md
  Projects/Astronomy/index.html
  Projects/Astronomy/index.js
  Projects/Astronomy/style.css
  assets/img/Astronomy.png
  projectData.json
Labels: New project, KWOC

#598 Made the Temperature Converter responsive
  Projects/Temperature_Converter/style.css
Labels: enhancement, KWOC

#603 added project
  Projects/Amazon-Clone/README.md
  Projects/Amazon-Clone/amazon_logo.png
  Projects/Amazon-Clone/box1_image.jpg
  Projects/Amazon-Clone/box2_image.jpg
  Projects/Amazon-Clone/box3_image.jpg
  Projects/Amazon-Clone/box4_image.jpg
  Projects/Amazon-Clone/box5_image.jpg
  Projects/Amazon-Clone/box6_image.jpg
  Projects/Amazon-Clone/box7_image.jpg
  Projects/Amazon-Clone/box8_image.jpg
  Projects/Amazon-Clone/hero2.jpeg
  Projects/Amazon-Clone/hero3.jpg
  Projects/Amazon-Clone/hero_image.jpg
  Projects/Amazon-Clone/index.html
  Projects/Amazon-Clone/style.css
  assets/img/Amazon-clone1.png
  projectData.json
Labels: KWOC

#601 Feat:adding darkmode in health dashboard
  Projects/Health Dashboard/index.html
  Projects/Health Dashboard/index.js
Labels: KWOC

#605 Made the Guess the number game responsive
  Projects/Guess_the_Number/style.css
Labels: enhancement, KWOC

#607 Made the Health Dashboard dynamic
  Projects/Health Dashboard/index.html
Labels: KWOC

#611 The Discover more button is fixed.
  Projects/NFT_Website_Clone/style.css
Labels: bug, KWOC
