Repository apu52/METAVERSE, pull requests merged in 2024-08, with the labels that each got.

#1151 Made Nav Bar Responsive for mobile view also
  index.html
  style.css
Labels: help wanted

#1167 About Section is changed for the Hostel Management System .
  Projects/HOSTEL_MANAGEMENT/index.html
  Projects/HOSTEL_MANAGEMENT/style.css
Labels: help wanted

#1183 enhance/our-menu/praveen
  Projects/Food_Ordering_Website/index.html
  Projects/Food_Ordering_Website/style.css
Labels: question, review requested

#1209 Text Reader Improvement Added
  Projects/Text-Reader/BG.webp
  Projects/Text-Reader/index.html
  Projects/Text-Reader/style.css
Labels: help wanted

#1200 Added RateUs Page
  RateUs.html
  index.html
Labels: help wanted

#1224 Added toggle navbar for mobile screen
  about.html
  contact.html
  contributor.html
  index.html
  style.css
Labels: changesrequested

#1227 feat: Added contact us page in the travel website project .
  Projects/Travel_Website/img/flat-design-illustration-customer-support_23-2148887720.avif
  Projects/Travel_Website/index.html
  Projects/Travel_Website/styles.css
Labels: changesrequested

#1230 Enhanced the UI for NewsApp and add User Authentication
  Projects/News app/client/.gitignore
  Projects/News app/client/README.md
  Projects/News app/client/package-lock.json
  Projects/News app/client/package.json
  Projects/News app/client/public/bg.jpg
  Projects/News app/client/public/index.html
  Projects/News app/client/public/manifest.json
  Projects/News app/client/public/robots.txt
  Projects/News app/client/src/App.css
  Projects/News app/client/src/App.js
  Projects/News app/client/src/Components/Auth.js
  Projects/News app/client/src/Components/Home.js
  Projects/News app/client/src/Components/Navbar.js
  Projects/News app/client/src/Components/News.js
  Projects/News app/client/src/Components/NewsCard.js
  Projects/News app/client/src/index.js
Labels: question

#1236 Fixed navbar at top and add hamburger menu for mobile screen
  assets/css/style.css
  index.html
  style.css
Labels: changesrequested
